name: JustTheRecipe
options:
  bundleIdPrefix: com.yuxuan
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: "1"
  DEVELOPMENT_TEAM: ""
  
targets:
  JustTheRecipe:
    type: application
    platform: iOS
    sources:
      - JustTheRecipe
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.yuxuan.justtherecipe
      INFOPLIST_FILE: JustTheRecipe/Info.plist
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      SWIFT_VERSION: "5.9"
    info:
      path: JustTheRecipe/Info.plist
      properties:
        CFBundleDisplayName: Pure Recipe
        CFBundleShortVersionString: "1.0.0"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
